### ISSUE TITLE
please can you add some Java script 

### ISSUE THREAD

**Issue by tomtgc** [RaspberryPiFoundation/ideas#11]
can you add some Java script please

**Comment by aldreth** [comment]
Hi @tomtgc thanks for your suggestion.

Code Club is part of the Raspberry Pi Foundation, which also has a lot of projects, and some of them use javascript.

A couple of suggestions would be:
* https://www.raspberrypi.org/learning/talk-like-a-pirate/
* https://www.raspberrypi.org/learning/cat-meme-generator/

Do you know any python? Lots of the Raspberry Pi projects use that language - it could be something else for you to try.

Happy coding!
Edward

**Comment by rik-cross** [comment]
Hi @tomtgc The 'Pixel Art' project also uses JavaScript:
https://codeclubprojects.org/en-GB/webdev/pixel-art/
